version: "3.7"

services:
  app:
    build:
      context: .
    image: recipe-app:latest
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      bash -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=rootroot
    depends_on:
      - db

  db:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootroot
#      - PGDATA=./pgdata
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata: